Finish implementation of fsfreeze hooks in K8s image

diff --git a/images/benji-k8s/scripts/benji-backup-pvc b/images/benji-k8s/scripts/benji-backup-pvc
--- a/images/benji-k8s/scripts/benji-backup-pvc
+++ b/images/benji-k8s/scripts/benji-backup-pvc
@@ -34,12 +34,22 @@ do
 	CEPH_RBD_IMAGE="$4"
 	VERSION_NAME="$K8S_PVC_NAMESPACE/$K8S_PVC_NAME"
 
-    K8S_PV_HOST_IP="$(kubectl -n "$K8S_PVC_NAMESPACE" get pod -o json | \
-        jq -r '[.items[] | . as $top | (.spec.volumes[] | select(.persistentVolumeClaim.claimName == "'"$K8S_PVC_NAME"'") | $top.status.hostIP)] | .[0] ?// ""')"
-    [[ $? == 0 ]] || continue
-
-    # Rook uses other directory
-    CEPH_RBD_IMAGE_MOUNTPOINT="/var/lib/kubelet/plugins/kubernetes.io/rbd/mounts/rbd-image-$CEPH_RBD_IMAGE"
+    FSFREEZE=$(kubectl get pvc -n "$K8S_PVC_NAMESPACE" "$K8S_PVC_NAME" -o json \
+                    | jq -r '.metadata.annotations["benji-backup.me/fsfreeze"] ?// "no"')
+    if [[ $FSFREEZE == "yes" ]]; then
+        K8S_PV_HOST_IP="$(kubectl -n "$K8S_PVC_NAMESPACE" get pod -o json | \
+            jq -r '[.items[] | . as $top | (.spec.volumes[] | select(.persistentVolumeClaim.claimName == "'"$K8S_PVC_NAME"'") | $top.status.hostIP)] | .[0] ?// ""')"
+        if [[ $? != 0 || $K8S_PV_HOST_IP == "" ]]; then
+            echo "Warning: Could not determine host where $K8S_PVC_NAMESPACE/$K8S_PVC_NAME is mounted."
+            FSFREEZE="no"
+        else
+            # Rook uses other directory
+            CEPH_RBD_IMAGE_MOUNTPOINT="/var/lib/kubelet/plugins/kubernetes.io/rbd/mounts/rbd-image-$CEPH_RBD_IMAGE"
+        fi
+    else
+        # Every other value than yes gets translated to no
+        FSFREEZE="no"
+    fi
 
 	benji::backup::ceph "$VERSION_NAME" "$CEPH_POOL" "$CEPH_RBD_IMAGE" \
             "benji-backup.me/instance=$BENJI_INSTANCE" \
